/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.21.5
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ViewColumn from './ViewColumn';

/**
 * The Branch model module.
 * @module com.gridly.api/model/Branch
 * @version 4.21.5
 */
class Branch {
    /**
     * Constructs a new <code>Branch</code>.
     * @alias module:com.gridly.api/model/Branch
     */
    constructor() { 
        
        Branch.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Branch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/Branch} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/Branch} The populated <code>Branch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Branch();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('columns')) {
                obj['columns'] = ApiClient.convertToType(data['columns'], [ViewColumn]);
            }
            if (data.hasOwnProperty('defaultAccessViewId')) {
                obj['defaultAccessViewId'] = ApiClient.convertToType(data['defaultAccessViewId'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': 'String'});
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('recordIdentifierType')) {
                obj['recordIdentifierType'] = ApiClient.convertToType(data['recordIdentifierType'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('isMaster')) {
                obj['isMaster'] = ApiClient.convertToType(data['isMaster'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Branch.prototype['id'] = undefined;

/**
 * @member {Array.<module:com.gridly.api/model/ViewColumn>} columns
 */
Branch.prototype['columns'] = undefined;

/**
 * @member {String} defaultAccessViewId
 */
Branch.prototype['defaultAccessViewId'] = undefined;

/**
 * @member {String} description
 */
Branch.prototype['description'] = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
Branch.prototype['metadata'] = undefined;

/**
 * @member {String} name
 */
Branch.prototype['name'] = undefined;

/**
 * @member {module:com.gridly.api/model/Branch.RecordIdentifierTypeEnum} recordIdentifierType
 */
Branch.prototype['recordIdentifierType'] = undefined;

/**
 * @member {module:com.gridly.api/model/Branch.StatusEnum} status
 */
Branch.prototype['status'] = undefined;

/**
 * @member {Boolean} isMaster
 */
Branch.prototype['isMaster'] = undefined;





/**
 * Allowed values for the <code>recordIdentifierType</code> property.
 * @enum {String}
 * @readonly
 */
Branch['RecordIdentifierTypeEnum'] = {

    /**
     * value: "recordId"
     * @const
     */
    "recordId": "recordId",

    /**
     * value: "pathTagRecordId"
     * @const
     */
    "pathTagRecordId": "pathTagRecordId"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Branch['StatusEnum'] = {

    /**
     * value: "deleted"
     * @const
     */
    "deleted": "deleted",

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "inactive"
     * @const
     */
    "inactive": "inactive",

    /**
     * value: "restoring"
     * @const
     */
    "restoring": "restoring",

    /**
     * value: "backingUp"
     * @const
     */
    "backingUp": "backingUp",

    /**
     * value: "uploading"
     * @const
     */
    "uploading": "uploading",

    /**
     * value: "importing"
     * @const
     */
    "importing": "importing",

    /**
     * value: "branching"
     * @const
     */
    "branching": "branching",

    /**
     * value: "merging"
     * @const
     */
    "merging": "merging",

    /**
     * value: "duplicating"
     * @const
     */
    "duplicating": "duplicating",

    /**
     * value: "clearingRecords"
     * @const
     */
    "clearingRecords": "clearingRecords"
};



export default Branch;

