/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.29.1
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TranslationCount from './TranslationCount';

/**
 * The ColumnStatistic model module.
 * @module com.gridly.api/model/ColumnStatistic
 * @version 4.29.1
 */
class ColumnStatistic {
    /**
     * Constructs a new <code>ColumnStatistic</code>.
     * @alias module:com.gridly.api/model/ColumnStatistic
     */
    constructor() { 
        
        ColumnStatistic.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ColumnStatistic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/ColumnStatistic} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/ColumnStatistic} The populated <code>ColumnStatistic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ColumnStatistic();

            if (data.hasOwnProperty('recordCount')) {
                obj['recordCount'] = TranslationCount.constructFromObject(data['recordCount']);
            }
            if (data.hasOwnProperty('wordCount')) {
                obj['wordCount'] = TranslationCount.constructFromObject(data['wordCount']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:com.gridly.api/model/TranslationCount} recordCount
 */
ColumnStatistic.prototype['recordCount'] = undefined;

/**
 * @member {module:com.gridly.api/model/TranslationCount} wordCount
 */
ColumnStatistic.prototype['wordCount'] = undefined;






export default ColumnStatistic;

