/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 5.9.0
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ExportFileHeader.
* @enum {}
* @readonly
*/
export default class ExportFileHeader {
    
        /**
         * value: "none"
         * @const
         */
        "none" = "none";

    
        /**
         * value: "columnName"
         * @const
         */
        "columnName" = "columnName";

    
        /**
         * value: "columnId"
         * @const
         */
        "columnId" = "columnId";

    

    /**
    * Returns a <code>ExportFileHeader</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:com.gridly.api/model/ExportFileHeader} The enum <code>ExportFileHeader</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

