/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.33.0
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GlossaryProject model module.
 * @module com.gridly.api/model/GlossaryProject
 * @version 4.33.0
 */
class GlossaryProject {
    /**
     * Constructs a new <code>GlossaryProject</code>.
     * @alias module:com.gridly.api/model/GlossaryProject
     */
    constructor() { 
        
        GlossaryProject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GlossaryProject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/GlossaryProject} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/GlossaryProject} The populated <code>GlossaryProject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GlossaryProject();

            if (data.hasOwnProperty('projectId')) {
                obj['projectId'] = ApiClient.convertToType(data['projectId'], 'Number');
            }
            if (data.hasOwnProperty('databaseIds')) {
                obj['databaseIds'] = ApiClient.convertToType(data['databaseIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GlossaryProject</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GlossaryProject</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['databaseIds'])) {
            throw new Error("Expected the field `databaseIds` to be an array in the JSON data but got " + data['databaseIds']);
        }

        return true;
    }


}



/**
 * @member {Number} projectId
 */
GlossaryProject.prototype['projectId'] = undefined;

/**
 * @member {Array.<String>} databaseIds
 */
GlossaryProject.prototype['databaseIds'] = undefined;






export default GlossaryProject;

