/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 5.9.0
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileCategory from './FileCategory';

/**
 * The GridSetting model module.
 * @module com.gridly.api/model/GridSetting
 * @version 5.9.0
 */
class GridSetting {
    /**
     * Constructs a new <code>GridSetting</code>.
     * @alias module:com.gridly.api/model/GridSetting
     */
    constructor() { 
        
        GridSetting.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GridSetting</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/GridSetting} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/GridSetting} The populated <code>GridSetting</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GridSetting();

            if (data.hasOwnProperty('defaultSourceLanguageStatus')) {
                obj['defaultSourceLanguageStatus'] = ApiClient.convertToType(data['defaultSourceLanguageStatus'], 'String');
            }
            if (data.hasOwnProperty('translatorCanViewAutomations')) {
                obj['translatorCanViewAutomations'] = ApiClient.convertToType(data['translatorCanViewAutomations'], 'Boolean');
            }
            if (data.hasOwnProperty('categories')) {
                obj['categories'] = ApiClient.convertToType(data['categories'], [FileCategory]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': 'String'});
            }
            if (data.hasOwnProperty('createdTime')) {
                obj['createdTime'] = ApiClient.convertToType(data['createdTime'], 'Date');
            }
            if (data.hasOwnProperty('lastModifiedTime')) {
                obj['lastModifiedTime'] = ApiClient.convertToType(data['lastModifiedTime'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('lastModifiedBy')) {
                obj['lastModifiedBy'] = ApiClient.convertToType(data['lastModifiedBy'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GridSetting</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GridSetting</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['defaultSourceLanguageStatus'] && !(typeof data['defaultSourceLanguageStatus'] === 'string' || data['defaultSourceLanguageStatus'] instanceof String)) {
            throw new Error("Expected the field `defaultSourceLanguageStatus` to be a primitive type in the JSON string but got " + data['defaultSourceLanguageStatus']);
        }
        if (data['categories']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['categories'])) {
                throw new Error("Expected the field `categories` to be an array in the JSON data but got " + data['categories']);
            }
            // validate the optional field `categories` (array)
            for (const item of data['categories']) {
                FileCategory.validateJsonObject(item);
            };
        }
        // ensure the json data is a string
        if (data['createdBy'] && !(typeof data['createdBy'] === 'string' || data['createdBy'] instanceof String)) {
            throw new Error("Expected the field `createdBy` to be a primitive type in the JSON string but got " + data['createdBy']);
        }
        // ensure the json data is a string
        if (data['lastModifiedBy'] && !(typeof data['lastModifiedBy'] === 'string' || data['lastModifiedBy'] instanceof String)) {
            throw new Error("Expected the field `lastModifiedBy` to be a primitive type in the JSON string but got " + data['lastModifiedBy']);
        }

        return true;
    }


}



/**
 * @member {module:com.gridly.api/model/GridSetting.DefaultSourceLanguageStatusEnum} defaultSourceLanguageStatus
 */
GridSetting.prototype['defaultSourceLanguageStatus'] = undefined;

/**
 * @member {Boolean} translatorCanViewAutomations
 */
GridSetting.prototype['translatorCanViewAutomations'] = undefined;

/**
 * @member {Array.<module:com.gridly.api/model/FileCategory>} categories
 */
GridSetting.prototype['categories'] = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
GridSetting.prototype['metadata'] = undefined;

/**
 * @member {Date} createdTime
 */
GridSetting.prototype['createdTime'] = undefined;

/**
 * @member {Date} lastModifiedTime
 */
GridSetting.prototype['lastModifiedTime'] = undefined;

/**
 * @member {String} createdBy
 */
GridSetting.prototype['createdBy'] = undefined;

/**
 * @member {String} lastModifiedBy
 */
GridSetting.prototype['lastModifiedBy'] = undefined;





/**
 * Allowed values for the <code>defaultSourceLanguageStatus</code> property.
 * @enum {String}
 * @readonly
 */
GridSetting['DefaultSourceLanguageStatusEnum'] = {

    /**
     * value: "unset"
     * @const
     */
    "unset": "unset",

    /**
     * value: "doNotTranslate"
     * @const
     */
    "doNotTranslate": "doNotTranslate",

    /**
     * value: "notReadyForTranslation"
     * @const
     */
    "notReadyForTranslation": "notReadyForTranslation",

    /**
     * value: "readyForTranslation"
     * @const
     */
    "readyForTranslation": "readyForTranslation",

    /**
     * value: "locked"
     * @const
     */
    "locked": "locked",

    /**
     * value: "lockAllLanguages"
     * @const
     */
    "lockAllLanguages": "lockAllLanguages"
};



export default GridSetting;

