/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.29.1
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FilterField from './FilterField';
import MergeRecordConflict from './MergeRecordConflict';

/**
 * The MergeBranchRequest model module.
 * @module com.gridly.api/model/MergeBranchRequest
 * @version 4.29.1
 */
class MergeBranchRequest {
    /**
     * Constructs a new <code>MergeBranchRequest</code>.
     * @alias module:com.gridly.api/model/MergeBranchRequest
     */
    constructor() { 
        
        MergeBranchRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MergeBranchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/MergeBranchRequest} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/MergeBranchRequest} The populated <code>MergeBranchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MergeBranchRequest();

            if (data.hasOwnProperty('mergeRecordOptions')) {
                obj['mergeRecordOptions'] = ApiClient.convertToType(data['mergeRecordOptions'], ['String']);
            }
            if (data.hasOwnProperty('mergeRecordConflicts')) {
                obj['mergeRecordConflicts'] = ApiClient.convertToType(data['mergeRecordConflicts'], [MergeRecordConflict]);
            }
            if (data.hasOwnProperty('useLastMergeResolve')) {
                obj['useLastMergeResolve'] = ApiClient.convertToType(data['useLastMergeResolve'], 'Boolean');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], [FilterField]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:com.gridly.api/model/MergeBranchRequest.MergeRecordOptionsEnum>} mergeRecordOptions
 */
MergeBranchRequest.prototype['mergeRecordOptions'] = undefined;

/**
 * @member {Array.<module:com.gridly.api/model/MergeRecordConflict>} mergeRecordConflicts
 */
MergeBranchRequest.prototype['mergeRecordConflicts'] = undefined;

/**
 * @member {Boolean} useLastMergeResolve
 */
MergeBranchRequest.prototype['useLastMergeResolve'] = undefined;

/**
 * @member {Array.<module:com.gridly.api/model/FilterField>} query
 */
MergeBranchRequest.prototype['query'] = undefined;





/**
 * Allowed values for the <code>mergeRecordOptions</code> property.
 * @enum {String}
 * @readonly
 */
MergeBranchRequest['MergeRecordOptionsEnum'] = {

    /**
     * value: "add"
     * @const
     */
    "add": "add",

    /**
     * value: "update"
     * @const
     */
    "update": "update",

    /**
     * value: "delete"
     * @const
     */
    "delete": "delete",

    /**
     * value: "override"
     * @const
     */
    "override": "override"
};



export default MergeBranchRequest;

