/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.21.5
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecordIdentifierWrapper model module.
 * @module com.gridly.api/model/RecordIdentifierWrapper
 * @version 4.21.5
 */
class RecordIdentifierWrapper {
    /**
     * Constructs a new <code>RecordIdentifierWrapper</code>.
     * @alias module:com.gridly.api/model/RecordIdentifierWrapper
     * @param id {String} 
     * @param path {String} 
     */
    constructor(id, path) { 
        
        RecordIdentifierWrapper.initialize(this, id, path);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, path) { 
        obj['id'] = id;
        obj['path'] = path;
    }

    /**
     * Constructs a <code>RecordIdentifierWrapper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/RecordIdentifierWrapper} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/RecordIdentifierWrapper} The populated <code>RecordIdentifierWrapper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecordIdentifierWrapper();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
RecordIdentifierWrapper.prototype['id'] = undefined;

/**
 * @member {String} path
 */
RecordIdentifierWrapper.prototype['path'] = undefined;






export default RecordIdentifierWrapper;

