/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 3.39.2
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Reference model module.
 * @module com.gridly.api/model/Reference
 * @version 3.39.2
 */
class Reference {
    /**
     * Constructs a new <code>Reference</code>.
     * @alias module:com.gridly.api/model/Reference
     * @param gridId {String} 
     * @param columnId {String} 
     */
    constructor(gridId, columnId) { 
        
        Reference.initialize(this, gridId, columnId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gridId, columnId) { 
        obj['gridId'] = gridId;
        obj['columnId'] = columnId;
    }

    /**
     * Constructs a <code>Reference</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/Reference} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/Reference} The populated <code>Reference</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Reference();

            if (data.hasOwnProperty('gridId')) {
                obj['gridId'] = ApiClient.convertToType(data['gridId'], 'String');
            }
            if (data.hasOwnProperty('columnId')) {
                obj['columnId'] = ApiClient.convertToType(data['columnId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('selectionType')) {
                obj['selectionType'] = ApiClient.convertToType(data['selectionType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} gridId
 */
Reference.prototype['gridId'] = undefined;

/**
 * @member {String} columnId
 */
Reference.prototype['columnId'] = undefined;

/**
 * @member {module:com.gridly.api/model/Reference.TypeEnum} type
 */
Reference.prototype['type'] = undefined;

/**
 * @member {module:com.gridly.api/model/Reference.SelectionTypeEnum} selectionType
 */
Reference.prototype['selectionType'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Reference['TypeEnum'] = {

    /**
     * value: "ROW"
     * @const
     */
    "ROW": "ROW",

    /**
     * value: "CELL"
     * @const
     */
    "CELL": "CELL"
};


/**
 * Allowed values for the <code>selectionType</code> property.
 * @enum {String}
 * @readonly
 */
Reference['SelectionTypeEnum'] = {

    /**
     * value: "SINGLE"
     * @const
     */
    "SINGLE": "SINGLE",

    /**
     * value: "MULTIPLE"
     * @const
     */
    "MULTIPLE": "MULTIPLE"
};



export default Reference;

