/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.15.1
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Privilege from './Privilege';

/**
 * The Role model module.
 * @module com.gridly.api/model/Role
 * @version 4.15.1
 */
class Role {
    /**
     * Constructs a new <code>Role</code>.
     * @alias module:com.gridly.api/model/Role
     */
    constructor() { 
        
        Role.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Role</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/Role} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/Role} The populated <code>Role</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Role();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('privileges')) {
                obj['privileges'] = ApiClient.convertToType(data['privileges'], [Privilege]);
            }
            if (data.hasOwnProperty('privilegeIds')) {
                obj['privilegeIds'] = ApiClient.convertToType(data['privilegeIds'], ['Number']);
            }
            if (data.hasOwnProperty('isSystemRole')) {
                obj['isSystemRole'] = ApiClient.convertToType(data['isSystemRole'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Role.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Role.prototype['name'] = undefined;

/**
 * @member {String} title
 */
Role.prototype['title'] = undefined;

/**
 * @member {String} type
 */
Role.prototype['type'] = undefined;

/**
 * @member {String} level
 */
Role.prototype['level'] = undefined;

/**
 * @member {Array.<module:com.gridly.api/model/Privilege>} privileges
 */
Role.prototype['privileges'] = undefined;

/**
 * @member {Array.<Number>} privilegeIds
 */
Role.prototype['privilegeIds'] = undefined;

/**
 * @member {Boolean} isSystemRole
 */
Role.prototype['isSystemRole'] = undefined;






export default Role;

