/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.29.1
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SetCell from './SetCell';

/**
 * The SetRecord model module.
 * @module com.gridly.api/model/SetRecord
 * @version 4.29.1
 */
class SetRecord {
    /**
     * Constructs a new <code>SetRecord</code>.
     * @alias module:com.gridly.api/model/SetRecord
     */
    constructor() { 
        
        SetRecord.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetRecord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/SetRecord} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/SetRecord} The populated <code>SetRecord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetRecord();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('cells')) {
                obj['cells'] = ApiClient.convertToType(data['cells'], [SetCell]);
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
SetRecord.prototype['id'] = undefined;

/**
 * @member {Array.<module:com.gridly.api/model/SetCell>} cells
 */
SetRecord.prototype['cells'] = undefined;

/**
 * @member {String} path
 */
SetRecord.prototype['path'] = undefined;






export default SetRecord;

