/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.21.5
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FileCategory from './FileCategory';
import UploadedFile from './UploadedFile';

/**
 * The SettingFile model module.
 * @module com.gridly.api/model/SettingFile
 * @version 4.21.5
 */
class SettingFile {
    /**
     * Constructs a new <code>SettingFile</code>.
     * @alias module:com.gridly.api/model/SettingFile
     */
    constructor() { 
        
        SettingFile.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SettingFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/SettingFile} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/SettingFile} The populated <code>SettingFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SettingFile();

            if (data.hasOwnProperty('category')) {
                obj['category'] = FileCategory.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], [UploadedFile]);
            }
        }
        return obj;
    }


}

/**
 * @member {module:com.gridly.api/model/FileCategory} category
 */
SettingFile.prototype['category'] = undefined;

/**
 * @member {Array.<module:com.gridly.api/model/UploadedFile>} files
 */
SettingFile.prototype['files'] = undefined;






export default SettingFile;

