/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.15.1
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TranslationStatus.
* @enum {}
* @readonly
*/
export default class TranslationStatus {
    
        /**
         * value: "upToDate"
         * @const
         */
        "upToDate" = "upToDate";

    
        /**
         * value: "outOfDate"
         * @const
         */
        "outOfDate" = "outOfDate";

    
        /**
         * value: "unset"
         * @const
         */
        "unset" = "unset";

    

    /**
    * Returns a <code>TranslationStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:com.gridly.api/model/TranslationStatus} The enum <code>TranslationStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

