/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.21.5
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DateTimeFormat from './DateTimeFormat';
import Formula from './Formula';
import NumberFormat from './NumberFormat';
import Reference from './Reference';

/**
 * The UpdateColumn model module.
 * @module com.gridly.api/model/UpdateColumn
 * @version 4.21.5
 */
class UpdateColumn {
    /**
     * Constructs a new <code>UpdateColumn</code>.
     * @alias module:com.gridly.api/model/UpdateColumn
     */
    constructor() { 
        
        UpdateColumn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateColumn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/UpdateColumn} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/UpdateColumn} The populated <code>UpdateColumn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateColumn();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('languageCode')) {
                obj['languageCode'] = ApiClient.convertToType(data['languageCode'], 'String');
            }
            if (data.hasOwnProperty('localizationType')) {
                obj['localizationType'] = ApiClient.convertToType(data['localizationType'], 'String');
            }
            if (data.hasOwnProperty('selectionOptions')) {
                obj['selectionOptions'] = ApiClient.convertToType(data['selectionOptions'], ['String']);
            }
            if (data.hasOwnProperty('numberFormat')) {
                obj['numberFormat'] = NumberFormat.constructFromObject(data['numberFormat']);
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = Reference.constructFromObject(data['reference']);
            }
            if (data.hasOwnProperty('formula')) {
                obj['formula'] = Formula.constructFromObject(data['formula']);
            }
            if (data.hasOwnProperty('dateTimeFormat')) {
                obj['dateTimeFormat'] = DateTimeFormat.constructFromObject(data['dateTimeFormat']);
            }
            if (data.hasOwnProperty('viewable')) {
                obj['viewable'] = ApiClient.convertToType(data['viewable'], 'Boolean');
            }
            if (data.hasOwnProperty('editable')) {
                obj['editable'] = ApiClient.convertToType(data['editable'], 'Boolean');
            }
            if (data.hasOwnProperty('newId')) {
                obj['newId'] = ApiClient.convertToType(data['newId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
UpdateColumn.prototype['name'] = undefined;

/**
 * @member {String} description
 */
UpdateColumn.prototype['description'] = undefined;

/**
 * @member {module:com.gridly.api/model/UpdateColumn.TypeEnum} type
 */
UpdateColumn.prototype['type'] = undefined;

/**
 * @member {module:com.gridly.api/model/UpdateColumn.LanguageCodeEnum} languageCode
 */
UpdateColumn.prototype['languageCode'] = undefined;

/**
 * @member {module:com.gridly.api/model/UpdateColumn.LocalizationTypeEnum} localizationType
 */
UpdateColumn.prototype['localizationType'] = undefined;

/**
 * @member {Array.<String>} selectionOptions
 */
UpdateColumn.prototype['selectionOptions'] = undefined;

/**
 * @member {module:com.gridly.api/model/NumberFormat} numberFormat
 */
UpdateColumn.prototype['numberFormat'] = undefined;

/**
 * @member {module:com.gridly.api/model/Reference} reference
 */
UpdateColumn.prototype['reference'] = undefined;

/**
 * @member {module:com.gridly.api/model/Formula} formula
 */
UpdateColumn.prototype['formula'] = undefined;

/**
 * @member {module:com.gridly.api/model/DateTimeFormat} dateTimeFormat
 */
UpdateColumn.prototype['dateTimeFormat'] = undefined;

/**
 * @member {Boolean} viewable
 */
UpdateColumn.prototype['viewable'] = undefined;

/**
 * @member {Boolean} editable
 */
UpdateColumn.prototype['editable'] = undefined;

/**
 * @member {String} newId
 */
UpdateColumn.prototype['newId'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
UpdateColumn['TypeEnum'] = {

    /**
     * value: "singleLine"
     * @const
     */
    "singleLine": "singleLine",

    /**
     * value: "multipleLines"
     * @const
     */
    "multipleLines": "multipleLines",

    /**
     * value: "richText"
     * @const
     */
    "richText": "richText",

    /**
     * value: "markdown"
     * @const
     */
    "markdown": "markdown",

    /**
     * value: "singleSelection"
     * @const
     */
    "singleSelection": "singleSelection",

    /**
     * value: "multipleSelections"
     * @const
     */
    "multipleSelections": "multipleSelections",

    /**
     * value: "boolean"
     * @const
     */
    "boolean": "boolean",

    /**
     * value: "number"
     * @const
     */
    "number": "number",

    /**
     * value: "datetime"
     * @const
     */
    "datetime": "datetime",

    /**
     * value: "files"
     * @const
     */
    "files": "files",

    /**
     * value: "reference"
     * @const
     */
    "reference": "reference",

    /**
     * value: "lookup"
     * @const
     */
    "lookup": "lookup",

    /**
     * value: "language"
     * @const
     */
    "language": "language",

    /**
     * value: "json"
     * @const
     */
    "json": "json",

    /**
     * value: "yaml"
     * @const
     */
    "yaml": "yaml",

    /**
     * value: "html"
     * @const
     */
    "html": "html",

    /**
     * value: "formula"
     * @const
     */
    "formula": "formula"
};


/**
 * Allowed values for the <code>languageCode</code> property.
 * @enum {String}
 * @readonly
 */
UpdateColumn['LanguageCodeEnum'] = {

    /**
     * value: "enUS"
     * @const
     */
    "enUS": "enUS",

    /**
     * value: "arSA"
     * @const
     */
    "arSA": "arSA",

    /**
     * value: "caES"
     * @const
     */
    "caES": "caES",

    /**
     * value: "zhCN"
     * @const
     */
    "zhCN": "zhCN",

    /**
     * value: "zhTW"
     * @const
     */
    "zhTW": "zhTW",

    /**
     * value: "deDE"
     * @const
     */
    "deDE": "deDE",

    /**
     * value: "itIT"
     * @const
     */
    "itIT": "itIT",

    /**
     * value: "jaJP"
     * @const
     */
    "jaJP": "jaJP",

    /**
     * value: "koKR"
     * @const
     */
    "koKR": "koKR",

    /**
     * value: "plPL"
     * @const
     */
    "plPL": "plPL",

    /**
     * value: "ptAO"
     * @const
     */
    "ptAO": "ptAO",

    /**
     * value: "ptBR"
     * @const
     */
    "ptBR": "ptBR",

    /**
     * value: "ruRU"
     * @const
     */
    "ruRU": "ruRU",

    /**
     * value: "esMX"
     * @const
     */
    "esMX": "esMX",

    /**
     * value: "esLA"
     * @const
     */
    "esLA": "esLA",

    /**
     * value: "esES"
     * @const
     */
    "esES": "esES",

    /**
     * value: "bnBD"
     * @const
     */
    "bnBD": "bnBD",

    /**
     * value: "bgBG"
     * @const
     */
    "bgBG": "bgBG",

    /**
     * value: "zhHK"
     * @const
     */
    "zhHK": "zhHK",

    /**
     * value: "csCZ"
     * @const
     */
    "csCZ": "csCZ",

    /**
     * value: "daDK"
     * @const
     */
    "daDK": "daDK",

    /**
     * value: "nlNL"
     * @const
     */
    "nlNL": "nlNL",

    /**
     * value: "fiFI"
     * @const
     */
    "fiFI": "fiFI",

    /**
     * value: "frFR"
     * @const
     */
    "frFR": "frFR",

    /**
     * value: "frCA"
     * @const
     */
    "frCA": "frCA",

    /**
     * value: "elGR"
     * @const
     */
    "elGR": "elGR",

    /**
     * value: "heIL"
     * @const
     */
    "heIL": "heIL",

    /**
     * value: "hiIN"
     * @const
     */
    "hiIN": "hiIN",

    /**
     * value: "huHU"
     * @const
     */
    "huHU": "huHU",

    /**
     * value: "idID"
     * @const
     */
    "idID": "idID",

    /**
     * value: "jwID"
     * @const
     */
    "jwID": "jwID",

    /**
     * value: "lvLV"
     * @const
     */
    "lvLV": "lvLV",

    /**
     * value: "msMY"
     * @const
     */
    "msMY": "msMY",

    /**
     * value: "noNO"
     * @const
     */
    "noNO": "noNO",

    /**
     * value: "ptPT"
     * @const
     */
    "ptPT": "ptPT",

    /**
     * value: "roRO"
     * @const
     */
    "roRO": "roRO",

    /**
     * value: "skSK"
     * @const
     */
    "skSK": "skSK",

    /**
     * value: "svSE"
     * @const
     */
    "svSE": "svSE",

    /**
     * value: "tlPH"
     * @const
     */
    "tlPH": "tlPH",

    /**
     * value: "thTH"
     * @const
     */
    "thTH": "thTH",

    /**
     * value: "trTR"
     * @const
     */
    "trTR": "trTR",

    /**
     * value: "ukUA"
     * @const
     */
    "ukUA": "ukUA",

    /**
     * value: "urIN"
     * @const
     */
    "urIN": "urIN",

    /**
     * value: "viVN"
     * @const
     */
    "viVN": "viVN",

    /**
     * value: "afZA"
     * @const
     */
    "afZA": "afZA",

    /**
     * value: "arAE"
     * @const
     */
    "arAE": "arAE",

    /**
     * value: "arBH"
     * @const
     */
    "arBH": "arBH",

    /**
     * value: "arDZ"
     * @const
     */
    "arDZ": "arDZ",

    /**
     * value: "arEG"
     * @const
     */
    "arEG": "arEG",

    /**
     * value: "arIQ"
     * @const
     */
    "arIQ": "arIQ",

    /**
     * value: "arJO"
     * @const
     */
    "arJO": "arJO",

    /**
     * value: "arKW"
     * @const
     */
    "arKW": "arKW",

    /**
     * value: "arLB"
     * @const
     */
    "arLB": "arLB",

    /**
     * value: "arLY"
     * @const
     */
    "arLY": "arLY",

    /**
     * value: "arMA"
     * @const
     */
    "arMA": "arMA",

    /**
     * value: "arOM"
     * @const
     */
    "arOM": "arOM",

    /**
     * value: "arQA"
     * @const
     */
    "arQA": "arQA",

    /**
     * value: "arSY"
     * @const
     */
    "arSY": "arSY",

    /**
     * value: "arTN"
     * @const
     */
    "arTN": "arTN",

    /**
     * value: "arYE"
     * @const
     */
    "arYE": "arYE",

    /**
     * value: "azAZ"
     * @const
     */
    "azAZ": "azAZ",

    /**
     * value: "beBY"
     * @const
     */
    "beBY": "beBY",

    /**
     * value: "bsBA"
     * @const
     */
    "bsBA": "bsBA",

    /**
     * value: "cyGB"
     * @const
     */
    "cyGB": "cyGB",

    /**
     * value: "deAT"
     * @const
     */
    "deAT": "deAT",

    /**
     * value: "deCH"
     * @const
     */
    "deCH": "deCH",

    /**
     * value: "deLI"
     * @const
     */
    "deLI": "deLI",

    /**
     * value: "deLU"
     * @const
     */
    "deLU": "deLU",

    /**
     * value: "dvMV"
     * @const
     */
    "dvMV": "dvMV",

    /**
     * value: "enAU"
     * @const
     */
    "enAU": "enAU",

    /**
     * value: "enBZ"
     * @const
     */
    "enBZ": "enBZ",

    /**
     * value: "enCA"
     * @const
     */
    "enCA": "enCA",

    /**
     * value: "enGB"
     * @const
     */
    "enGB": "enGB",

    /**
     * value: "enIE"
     * @const
     */
    "enIE": "enIE",

    /**
     * value: "enJM"
     * @const
     */
    "enJM": "enJM",

    /**
     * value: "enNZ"
     * @const
     */
    "enNZ": "enNZ",

    /**
     * value: "enPH"
     * @const
     */
    "enPH": "enPH",

    /**
     * value: "enTT"
     * @const
     */
    "enTT": "enTT",

    /**
     * value: "enZA"
     * @const
     */
    "enZA": "enZA",

    /**
     * value: "enZW"
     * @const
     */
    "enZW": "enZW",

    /**
     * value: "enSG"
     * @const
     */
    "enSG": "enSG",

    /**
     * value: "enIN"
     * @const
     */
    "enIN": "enIN",

    /**
     * value: "enGH"
     * @const
     */
    "enGH": "enGH",

    /**
     * value: "enRW"
     * @const
     */
    "enRW": "enRW",

    /**
     * value: "enZM"
     * @const
     */
    "enZM": "enZM",

    /**
     * value: "enKE"
     * @const
     */
    "enKE": "enKE",

    /**
     * value: "enNG"
     * @const
     */
    "enNG": "enNG",

    /**
     * value: "esAR"
     * @const
     */
    "esAR": "esAR",

    /**
     * value: "esBO"
     * @const
     */
    "esBO": "esBO",

    /**
     * value: "esCL"
     * @const
     */
    "esCL": "esCL",

    /**
     * value: "esCO"
     * @const
     */
    "esCO": "esCO",

    /**
     * value: "esCR"
     * @const
     */
    "esCR": "esCR",

    /**
     * value: "esDO"
     * @const
     */
    "esDO": "esDO",

    /**
     * value: "esEC"
     * @const
     */
    "esEC": "esEC",

    /**
     * value: "esGT"
     * @const
     */
    "esGT": "esGT",

    /**
     * value: "esHN"
     * @const
     */
    "esHN": "esHN",

    /**
     * value: "esNI"
     * @const
     */
    "esNI": "esNI",

    /**
     * value: "esPA"
     * @const
     */
    "esPA": "esPA",

    /**
     * value: "esPE"
     * @const
     */
    "esPE": "esPE",

    /**
     * value: "esPR"
     * @const
     */
    "esPR": "esPR",

    /**
     * value: "esPY"
     * @const
     */
    "esPY": "esPY",

    /**
     * value: "esSV"
     * @const
     */
    "esSV": "esSV",

    /**
     * value: "esUY"
     * @const
     */
    "esUY": "esUY",

    /**
     * value: "esVE"
     * @const
     */
    "esVE": "esVE",

    /**
     * value: "etEE"
     * @const
     */
    "etEE": "etEE",

    /**
     * value: "euES"
     * @const
     */
    "euES": "euES",

    /**
     * value: "faIR"
     * @const
     */
    "faIR": "faIR",

    /**
     * value: "foFO"
     * @const
     */
    "foFO": "foFO",

    /**
     * value: "frBE"
     * @const
     */
    "frBE": "frBE",

    /**
     * value: "frCH"
     * @const
     */
    "frCH": "frCH",

    /**
     * value: "frLU"
     * @const
     */
    "frLU": "frLU",

    /**
     * value: "frMC"
     * @const
     */
    "frMC": "frMC",

    /**
     * value: "glES"
     * @const
     */
    "glES": "glES",

    /**
     * value: "guIN"
     * @const
     */
    "guIN": "guIN",

    /**
     * value: "hrBA"
     * @const
     */
    "hrBA": "hrBA",

    /**
     * value: "hrHR"
     * @const
     */
    "hrHR": "hrHR",

    /**
     * value: "hyAM"
     * @const
     */
    "hyAM": "hyAM",

    /**
     * value: "isIS"
     * @const
     */
    "isIS": "isIS",

    /**
     * value: "itCH"
     * @const
     */
    "itCH": "itCH",

    /**
     * value: "kaGE"
     * @const
     */
    "kaGE": "kaGE",

    /**
     * value: "kkKZ"
     * @const
     */
    "kkKZ": "kkKZ",

    /**
     * value: "knIN"
     * @const
     */
    "knIN": "knIN",

    /**
     * value: "kokIN"
     * @const
     */
    "kokIN": "kokIN",

    /**
     * value: "kyKG"
     * @const
     */
    "kyKG": "kyKG",

    /**
     * value: "ltLT"
     * @const
     */
    "ltLT": "ltLT",

    /**
     * value: "miNZ"
     * @const
     */
    "miNZ": "miNZ",

    /**
     * value: "mkMK"
     * @const
     */
    "mkMK": "mkMK",

    /**
     * value: "mnMN"
     * @const
     */
    "mnMN": "mnMN",

    /**
     * value: "mrIN"
     * @const
     */
    "mrIN": "mrIN",

    /**
     * value: "msBN"
     * @const
     */
    "msBN": "msBN",

    /**
     * value: "mtMT"
     * @const
     */
    "mtMT": "mtMT",

    /**
     * value: "nbNO"
     * @const
     */
    "nbNO": "nbNO",

    /**
     * value: "nlBE"
     * @const
     */
    "nlBE": "nlBE",

    /**
     * value: "nnNO"
     * @const
     */
    "nnNO": "nnNO",

    /**
     * value: "nsZA"
     * @const
     */
    "nsZA": "nsZA",

    /**
     * value: "paIN"
     * @const
     */
    "paIN": "paIN",

    /**
     * value: "psAR"
     * @const
     */
    "psAR": "psAR",

    /**
     * value: "quBO"
     * @const
     */
    "quBO": "quBO",

    /**
     * value: "quEC"
     * @const
     */
    "quEC": "quEC",

    /**
     * value: "quPE"
     * @const
     */
    "quPE": "quPE",

    /**
     * value: "saIN"
     * @const
     */
    "saIN": "saIN",

    /**
     * value: "seFI"
     * @const
     */
    "seFI": "seFI",

    /**
     * value: "seNO"
     * @const
     */
    "seNO": "seNO",

    /**
     * value: "seSE"
     * @const
     */
    "seSE": "seSE",

    /**
     * value: "slSI"
     * @const
     */
    "slSI": "slSI",

    /**
     * value: "sqAL"
     * @const
     */
    "sqAL": "sqAL",

    /**
     * value: "srBA"
     * @const
     */
    "srBA": "srBA",

    /**
     * value: "srRS"
     * @const
     */
    "srRS": "srRS",

    /**
     * value: "srME"
     * @const
     */
    "srME": "srME",

    /**
     * value: "svFI"
     * @const
     */
    "svFI": "svFI",

    /**
     * value: "swKE"
     * @const
     */
    "swKE": "swKE",

    /**
     * value: "syrSY"
     * @const
     */
    "syrSY": "syrSY",

    /**
     * value: "taIN"
     * @const
     */
    "taIN": "taIN",

    /**
     * value: "teIN"
     * @const
     */
    "teIN": "teIN",

    /**
     * value: "tnZA"
     * @const
     */
    "tnZA": "tnZA",

    /**
     * value: "ttRU"
     * @const
     */
    "ttRU": "ttRU",

    /**
     * value: "urPK"
     * @const
     */
    "urPK": "urPK",

    /**
     * value: "uzUZ"
     * @const
     */
    "uzUZ": "uzUZ",

    /**
     * value: "xhZA"
     * @const
     */
    "xhZA": "xhZA",

    /**
     * value: "zhMO"
     * @const
     */
    "zhMO": "zhMO",

    /**
     * value: "zhSG"
     * @const
     */
    "zhSG": "zhSG",

    /**
     * value: "zuZA"
     * @const
     */
    "zuZA": "zuZA",

    /**
     * value: "am"
     * @const
     */
    "am": "am",

    /**
     * value: "hy"
     * @const
     */
    "hy": "hy",

    /**
     * value: "az"
     * @const
     */
    "az": "az",

    /**
     * value: "bn"
     * @const
     */
    "bn": "bn",

    /**
     * value: "bs"
     * @const
     */
    "bs": "bs",

    /**
     * value: "ca"
     * @const
     */
    "ca": "ca",

    /**
     * value: "hr"
     * @const
     */
    "hr": "hr",

    /**
     * value: "da"
     * @const
     */
    "da": "da",

    /**
     * value: "nl"
     * @const
     */
    "nl": "nl",

    /**
     * value: "en"
     * @const
     */
    "en": "en",

    /**
     * value: "fi"
     * @const
     */
    "fi": "fi",

    /**
     * value: "fr"
     * @const
     */
    "fr": "fr",

    /**
     * value: "hi"
     * @const
     */
    "hi": "hi",

    /**
     * value: "hu"
     * @const
     */
    "hu": "hu",

    /**
     * value: "id"
     * @const
     */
    "id": "id",

    /**
     * value: "it"
     * @const
     */
    "it": "it",

    /**
     * value: "km"
     * @const
     */
    "km": "km",

    /**
     * value: "mi"
     * @const
     */
    "mi": "mi",

    /**
     * value: "ps"
     * @const
     */
    "ps": "ps",

    /**
     * value: "ru"
     * @const
     */
    "ru": "ru",

    /**
     * value: "sl"
     * @const
     */
    "sl": "sl",

    /**
     * value: "es"
     * @const
     */
    "es": "es",

    /**
     * value: "sw"
     * @const
     */
    "sw": "sw",

    /**
     * value: "ta"
     * @const
     */
    "ta": "ta",

    /**
     * value: "ur"
     * @const
     */
    "ur": "ur",

    /**
     * value: "af"
     * @const
     */
    "af": "af",

    /**
     * value: "et"
     * @const
     */
    "et": "et",

    /**
     * value: "gl"
     * @const
     */
    "gl": "gl",

    /**
     * value: "ja"
     * @const
     */
    "ja": "ja",

    /**
     * value: "kk"
     * @const
     */
    "kk": "kk",

    /**
     * value: "ky"
     * @const
     */
    "ky": "ky",

    /**
     * value: "mk"
     * @const
     */
    "mk": "mk",

    /**
     * value: "ms"
     * @const
     */
    "ms": "ms",

    /**
     * value: "se"
     * @const
     */
    "se": "se",

    /**
     * value: "pl"
     * @const
     */
    "pl": "pl",

    /**
     * value: "pa"
     * @const
     */
    "pa": "pa",

    /**
     * value: "ro"
     * @const
     */
    "ro": "ro",

    /**
     * value: "sk"
     * @const
     */
    "sk": "sk",

    /**
     * value: "sv"
     * @const
     */
    "sv": "sv",

    /**
     * value: "tt"
     * @const
     */
    "tt": "tt",

    /**
     * value: "te"
     * @const
     */
    "te": "te",

    /**
     * value: "tr"
     * @const
     */
    "tr": "tr",

    /**
     * value: "uz"
     * @const
     */
    "uz": "uz",

    /**
     * value: "vi"
     * @const
     */
    "vi": "vi",

    /**
     * value: "eu"
     * @const
     */
    "eu": "eu",

    /**
     * value: "be"
     * @const
     */
    "be": "be",

    /**
     * value: "cs"
     * @const
     */
    "cs": "cs",

    /**
     * value: "de"
     * @const
     */
    "de": "de",

    /**
     * value: "gu"
     * @const
     */
    "gu": "gu",

    /**
     * value: "he"
     * @const
     */
    "he": "he",

    /**
     * value: "is"
     * @const
     */
    "is": "is",

    /**
     * value: "ko"
     * @const
     */
    "ko": "ko",

    /**
     * value: "lt"
     * @const
     */
    "lt": "lt",

    /**
     * value: "mr"
     * @const
     */
    "mr": "mr",

    /**
     * value: "mn"
     * @const
     */
    "mn": "mn",

    /**
     * value: "nb"
     * @const
     */
    "nb": "nb",

    /**
     * value: "nn"
     * @const
     */
    "nn": "nn",

    /**
     * value: "pt"
     * @const
     */
    "pt": "pt",

    /**
     * value: "sa"
     * @const
     */
    "sa": "sa",

    /**
     * value: "tn"
     * @const
     */
    "tn": "tn",

    /**
     * value: "uk"
     * @const
     */
    "uk": "uk",

    /**
     * value: "xh"
     * @const
     */
    "xh": "xh",

    /**
     * value: "sq"
     * @const
     */
    "sq": "sq",

    /**
     * value: "ar"
     * @const
     */
    "ar": "ar",

    /**
     * value: "bg"
     * @const
     */
    "bg": "bg",

    /**
     * value: "zh"
     * @const
     */
    "zh": "zh",

    /**
     * value: "dv"
     * @const
     */
    "dv": "dv",

    /**
     * value: "fo"
     * @const
     */
    "fo": "fo",

    /**
     * value: "fa"
     * @const
     */
    "fa": "fa",

    /**
     * value: "ka"
     * @const
     */
    "ka": "ka",

    /**
     * value: "el"
     * @const
     */
    "el": "el",

    /**
     * value: "kn"
     * @const
     */
    "kn": "kn",

    /**
     * value: "lv"
     * @const
     */
    "lv": "lv",

    /**
     * value: "mt"
     * @const
     */
    "mt": "mt",

    /**
     * value: "qu"
     * @const
     */
    "qu": "qu",

    /**
     * value: "sr"
     * @const
     */
    "sr": "sr",

    /**
     * value: "si"
     * @const
     */
    "si": "si",

    /**
     * value: "tl"
     * @const
     */
    "tl": "tl",

    /**
     * value: "th"
     * @const
     */
    "th": "th",

    /**
     * value: "cy"
     * @const
     */
    "cy": "cy",

    /**
     * value: "zu"
     * @const
     */
    "zu": "zu",

    /**
     * value: "no"
     * @const
     */
    "no": "no"
};


/**
 * Allowed values for the <code>localizationType</code> property.
 * @enum {String}
 * @readonly
 */
UpdateColumn['LocalizationTypeEnum'] = {

    /**
     * value: "sourceLanguage"
     * @const
     */
    "sourceLanguage": "sourceLanguage",

    /**
     * value: "targetLanguage"
     * @const
     */
    "targetLanguage": "targetLanguage"
};



export default UpdateColumn;

