/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.33.0
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateDependency model module.
 * @module com.gridly.api/model/UpdateDependency
 * @version 4.33.0
 */
class UpdateDependency {
    /**
     * Constructs a new <code>UpdateDependency</code>.
     * @alias module:com.gridly.api/model/UpdateDependency
     * @param targetColumnId {String} 
     * @param sourceColumnId {String} 
     */
    constructor(targetColumnId, sourceColumnId) { 
        
        UpdateDependency.initialize(this, targetColumnId, sourceColumnId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, targetColumnId, sourceColumnId) { 
        obj['targetColumnId'] = targetColumnId;
        obj['sourceColumnId'] = sourceColumnId;
    }

    /**
     * Constructs a <code>UpdateDependency</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/UpdateDependency} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/UpdateDependency} The populated <code>UpdateDependency</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDependency();

            if (data.hasOwnProperty('newId')) {
                obj['newId'] = ApiClient.convertToType(data['newId'], 'String');
            }
            if (data.hasOwnProperty('targetColumnId')) {
                obj['targetColumnId'] = ApiClient.convertToType(data['targetColumnId'], 'String');
            }
            if (data.hasOwnProperty('sourceColumnId')) {
                obj['sourceColumnId'] = ApiClient.convertToType(data['sourceColumnId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateDependency</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateDependency</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateDependency.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['newId'] && !(typeof data['newId'] === 'string' || data['newId'] instanceof String)) {
            throw new Error("Expected the field `newId` to be a primitive type in the JSON string but got " + data['newId']);
        }
        // ensure the json data is a string
        if (data['targetColumnId'] && !(typeof data['targetColumnId'] === 'string' || data['targetColumnId'] instanceof String)) {
            throw new Error("Expected the field `targetColumnId` to be a primitive type in the JSON string but got " + data['targetColumnId']);
        }
        // ensure the json data is a string
        if (data['sourceColumnId'] && !(typeof data['sourceColumnId'] === 'string' || data['sourceColumnId'] instanceof String)) {
            throw new Error("Expected the field `sourceColumnId` to be a primitive type in the JSON string but got " + data['sourceColumnId']);
        }

        return true;
    }


}

UpdateDependency.RequiredProperties = ["targetColumnId", "sourceColumnId"];

/**
 * @member {String} newId
 */
UpdateDependency.prototype['newId'] = undefined;

/**
 * @member {String} targetColumnId
 */
UpdateDependency.prototype['targetColumnId'] = undefined;

/**
 * @member {String} sourceColumnId
 */
UpdateDependency.prototype['sourceColumnId'] = undefined;






export default UpdateDependency;

