/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 3.39.2
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateGrid model module.
 * @module com.gridly.api/model/UpdateGrid
 * @version 3.39.2
 */
class UpdateGrid {
    /**
     * Constructs a new <code>UpdateGrid</code>.
     * @alias module:com.gridly.api/model/UpdateGrid
     */
    constructor() { 
        
        UpdateGrid.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateGrid</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/UpdateGrid} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/UpdateGrid} The populated <code>UpdateGrid</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateGrid();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], {'String': 'String'});
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
UpdateGrid.prototype['name'] = undefined;

/**
 * @member {Object.<String, String>} metadata
 */
UpdateGrid.prototype['metadata'] = undefined;






export default UpdateGrid;

