/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.29.1
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GlossaryProject from './GlossaryProject';

/**
 * The UpdateGlossary model module.
 * @module com.gridly.api/model/UpdateGlossary
 * @version 4.29.1
 */
class UpdateGlossary {
    /**
     * Constructs a new <code>UpdateGlossary</code>.
     * @alias module:com.gridly.api/model/UpdateGlossary
     */
    constructor() { 
        
        UpdateGlossary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateGlossary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/UpdateGlossary} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/UpdateGlossary} The populated <code>UpdateGlossary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateGlossary();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('langs')) {
                obj['langs'] = ApiClient.convertToType(data['langs'], ['String']);
            }
            if (data.hasOwnProperty('projects')) {
                obj['projects'] = ApiClient.convertToType(data['projects'], [GlossaryProject]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
UpdateGlossary.prototype['name'] = undefined;

/**
 * @member {String} description
 */
UpdateGlossary.prototype['description'] = undefined;

/**
 * @member {Array.<String>} langs
 */
UpdateGlossary.prototype['langs'] = undefined;

/**
 * @member {Array.<module:com.gridly.api/model/GlossaryProject>} projects
 */
UpdateGlossary.prototype['projects'] = undefined;






export default UpdateGlossary;

