/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.29.1
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UploadedFile model module.
 * @module com.gridly.api/model/UploadedFile
 * @version 4.29.1
 */
class UploadedFile {
    /**
     * Constructs a new <code>UploadedFile</code>.
     * @alias module:com.gridly.api/model/UploadedFile
     */
    constructor() { 
        
        UploadedFile.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UploadedFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/UploadedFile} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/UploadedFile} The populated <code>UploadedFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UploadedFile();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('originalName')) {
                obj['originalName'] = ApiClient.convertToType(data['originalName'], 'String');
            }
            if (data.hasOwnProperty('contentType')) {
                obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('thumbnailId')) {
                obj['thumbnailId'] = ApiClient.convertToType(data['thumbnailId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UploadedFile.prototype['id'] = undefined;

/**
 * @member {String} originalName
 */
UploadedFile.prototype['originalName'] = undefined;

/**
 * @member {String} contentType
 */
UploadedFile.prototype['contentType'] = undefined;

/**
 * @member {Number} size
 */
UploadedFile.prototype['size'] = undefined;

/**
 * @member {String} thumbnailId
 */
UploadedFile.prototype['thumbnailId'] = undefined;






export default UploadedFile;

