/**
 * Gridly API
 * Gridly API documentation
 *
 * The version of the OpenAPI document: 4.33.0
 * Contact: support@gridly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UploadZipRequest model module.
 * @module com.gridly.api/model/UploadZipRequest
 * @version 4.33.0
 */
class UploadZipRequest {
    /**
     * Constructs a new <code>UploadZipRequest</code>.
     * @alias module:com.gridly.api/model/UploadZipRequest
     * @param columnId {String} 
     * @param fileMappings {String} 
     * @param file {File} 
     */
    constructor(columnId, fileMappings, file) { 
        
        UploadZipRequest.initialize(this, columnId, fileMappings, file);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, columnId, fileMappings, file) { 
        obj['columnId'] = columnId;
        obj['fileMappings'] = fileMappings;
        obj['file'] = file;
    }

    /**
     * Constructs a <code>UploadZipRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.gridly.api/model/UploadZipRequest} obj Optional instance to populate.
     * @return {module:com.gridly.api/model/UploadZipRequest} The populated <code>UploadZipRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UploadZipRequest();

            if (data.hasOwnProperty('columnId')) {
                obj['columnId'] = ApiClient.convertToType(data['columnId'], 'String');
            }
            if (data.hasOwnProperty('fileMappings')) {
                obj['fileMappings'] = ApiClient.convertToType(data['fileMappings'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], File);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UploadZipRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UploadZipRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UploadZipRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['columnId'] && !(typeof data['columnId'] === 'string' || data['columnId'] instanceof String)) {
            throw new Error("Expected the field `columnId` to be a primitive type in the JSON string but got " + data['columnId']);
        }
        // ensure the json data is a string
        if (data['fileMappings'] && !(typeof data['fileMappings'] === 'string' || data['fileMappings'] instanceof String)) {
            throw new Error("Expected the field `fileMappings` to be a primitive type in the JSON string but got " + data['fileMappings']);
        }

        return true;
    }


}

UploadZipRequest.RequiredProperties = ["columnId", "fileMappings", "file"];

/**
 * @member {String} columnId
 */
UploadZipRequest.prototype['columnId'] = undefined;

/**
 * @member {String} fileMappings
 */
UploadZipRequest.prototype['fileMappings'] = undefined;

/**
 * @member {File} file
 */
UploadZipRequest.prototype['file'] = undefined;






export default UploadZipRequest;

